apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../../components/cp4d/control-plane/variants/storage/ibm-classic

resources:
- ../../../components/cp4d/control-plane/base
